* ============================================================
* PRBS7 eye diagram bench — transistor-level reference SPICE
* 200 Mbps (5 ns UI), 200 bits = 1000 ns
* ============================================================

.temp 27
.options method=gear maxord=2 reltol=1e-3 abstol=1e-9 vntol=1e-5 gmin=1e-10 trtol=10

* V-source PWL: ngspice queues breakpoints as timestep events (fast)
* Generated by scripts/gen_prbs7.py
.include 'prbs7_vstim.inc'
Rin    in_src  in_dig  1

Vdd_ref  vdd_ref_src  0  DC 3.3
Voe_ref  oe_ref_src   0  DC 3.3
Rvdd_ref vdd_ref_src  vdd_ref  1
Roe_ref  oe_ref_src   oe_ref   1
Cdec_ref vdd_ref      0        10p

.subckt SPICE_BUF in oe out in_sense vdd vss
.include '../models/hspice_ngspice.mod'
.include '../models/io_buf.sp'
.ends SPICE_BUF

XREF in_dig oe_ref pad_ref in_sense_ref vdd_ref 0 SPICE_BUF

T1  pad_ref  0  ntst_ref  0  Z0=50 Td=30p
R1  ntst_ref 0  50

.save V(in_dig) V(pad_ref) V(ntst_ref) V(in_sense_ref)
.ic V(pad_ref)=0 V(ntst_ref)=0
.tran 10p 20n uic

.end

