#!/usr/bin/env python3
"""Where is the simulated waveform for each of the 12 final file-only builds?

The 09-23 summary reports one number per buffer (the worst stressed peak error). Every one of
those numbers comes from a simulation whose pad waveform was plotted at the time, into
`chain.png` beside the build - transistor, shipped model and our chain, at each stressed width.
Those figures are scattered across two step folders and 12 build directories, so this collects
them into one table with the per-width errors from each build's own `sweep.csv`.

It reads only what is already on disk; it runs no simulation and recomputes nothing.

Output: results/track1_summary_2026-09-23/WAVEFORMS.md

    py -3.14 scripts/track1_waveform_index.py
"""
from __future__ import annotations

import csv
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for _p in (ROOT / "scripts", ROOT / "tools" / "pybis2spice"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import stage_count_from_file as sc  # noqa: E402

OUT = ROOT / "results" / "track1_summary_2026-09-23" / "WAVEFORMS.md"
PICKS = ROOT / "results" / "selector_from_one_run_2026-09-23" / "selector_picks.csv"

HEAD = """# The simulated waveforms behind the 12 numbers

*Generated by `python scripts/track1_waveform_index.py`; no simulation, no recomputation.*

Every buffer's headline number is the worst of five (or seven) stressed runs, and each of those
runs was plotted when it was made. `chain.png` beside each build is that plot:

* **columns** - one per stressed pulse width, widest (least stressed) on the left;
* **top row** - the command gate: the transistor's probed gate in black, the shipped model's
  GUP dotted grey, our chain's GUP dashed red, and the Ku it produces in orange. The black
  trace is only available for the three probed buffers (`ex2`, `inv_chain`, `io_buf`); on the
  nine variants the top row shows our gate alone;
* **bottom row** - the pad, which is the thing being graded: transistor in black, shipped model
  dotted grey, our chain dashed green, each labelled with its own peak error;
* **x axis** - time from the reversal, -0.5 to +3 ns.

"shipped" is the converter's own model (`pybis2spice`'s
`InputDrivenTwoStateGateDelayCommandFull`) run in ngspice - our previous generation, not HSPICE
native IBIS.

The `d<n>` folders beside each `chain.png` hold the deck, log and `run.raw` of each of those
runs, so any of them can be replotted without re-simulating.

"""


# Two shipped rows were scored from a run a parallel worker had not finished writing, and read
# -100 % with a gate maximum of 0.00. These are the values re-scored from the stored raws
# (scratchpad, 2026-09-23); the section at the foot of the file says what happened.
SHIP_FIX = {"ex2_weak": {"d80": "+15.1 %†", "d60": "+47.2 %†"}}


def main() -> int:
    picks = list(csv.DictReader(PICKS.open(encoding="utf-8")))
    lines, detail = [], []
    for r in picks:
        dev = r["buffer"]
        kk, sh = r["rms"].split(" ")
        K = int(kk[1:])
        vt, al = (float(x) for x in sh.split("/"))
        b = sc.BUFFERS[dev]
        kd = sc.plateau_band(dev, "pull-down")[0] if b["k_net"][1] is not None else None
        d = sc.build_dir("step8", dev, K, kd, (vt, al)) or sc.build_dir("step6", dev, K, kd)
        if d is None:
            lines.append(f"| `{dev}` | K{K} {sh} | - | **build not found** |")
            continue
        rows = list(csv.DictReader((d / "sweep.csv").open(encoding="utf-8")))
        ours, ship = rows[-1], rows[0]
        cases = [k[3:] for k in ours if k.startswith("pk_d")]
        # links resolve from this file's own folder, not from the repo root
        fig = os.path.relpath(d / "chain.png", OUT.parent).replace("\\", "/")
        lines.append(f"| `{dev}` | K{K}, shape {sh} | {r['rms_pct']} % | [chain.png]({fig}) |")
        detail.append((dev, cases,
                       [ours[f"pk_{c}"] for c in cases],
                       [SHIP_FIX.get(dev, {}).get(c, ship[f"pk_{c}"]) for c in cases],
                       ours["full_pad_rms_mV"], ship["full_pad_rms_mV"]))

    body = ["## The figure for each buffer\n",
            "| buffer | the build the recipe chose | worst stressed peak | waveforms |",
            "|---|---|---:|---|"] + lines + [""]

    body += ["## Peak error at every stressed level\n",
             "Each column is one stressed pulse; the label is the depth target (per cent of the",
             "transistor's own settled swing reached before the input reverses) or, for the three",
             "probed buffers, the pulse width in ps. Left column = least stressed.\n"]
    for dev, cases, po, ps, fo, fs in detail:
        body.append(f"**{dev}** - full-swing pad rms: ours {fo} mV, shipped {fs} mV\n")
        body.append("| | " + " | ".join(f"`{c}`" for c in cases) + " |")
        body.append("|---|" + "---:|" * len(cases))
        body.append("| ours | " + " | ".join(f"{v} %" for v in po) + " |")
        body.append("| shipped | " + " | ".join(v if v.endswith(("%", "†")) else f"{v} %" for v in ps) + " |")
        body.append("")

    body += ["## What the stress axis covers, and what it does not\n",
             "The five (seven) levels above are the whole of the stress axis these numbers are",
             "scored on. Everything else about the bench is held at one value:\n",
             "| axis | covered | not covered |",
             "|---|---|---|",
             "| depth | 50, 60, 70, 80, 90 % of the transistor's own settled swing; `inv_base8` and "
             "`inv_stage4` also 85 and 100 % | below 50 %, where the pad barely leaves the rail |",
             "| direction | short **HIGH** (the pad is driven up and the input reverses on the way) | "
             "short LOW on 11 of 12; only `io_buf` has been run in the pull-down direction "
             "(`io_buf_pulldown_depth_2026-09-22`, 16-21 points shallow) |",
             "| pulses | one | trains (`train_check_today_2026-09-23`: the shipped model still wins "
             "on `ex2` and `io_buf`) |",
             "| load | 50 ohm to ground in parallel with 2 pF | any other load |",
             "| input edge | 50 ps on `ex2` / `inv_chain` / `io_buf`, 1 ps on the nine variants | "
             "a sweep of edge rate at fixed width |",
             "| corner | Typical only | Min / Max, supply or temperature corners |",
             "",
             "The depth ladder itself is a measured quantity, not a set of nominal widths: each width",
             "was chosen from the transistor's own depth-versus-width curve so that the achieved",
             "depth lands on the target (`results/variant_stress_cases_2026-09-04/cases.csv` records",
             "both, and they agree to within 1 point).",
             "",
             "One thing the ladder is not uniform in: `io_buf` at its 50 % level has the pad only 37 %",
             "of the way up at the reversal, while the other eleven reach the reversal with the gate",
             "fully on. That is the two-regime split recorded in the 09-08 work, and it is why",
             "`io_buf` behaves unlike the rest here.\n"]

    body += ["## † Two shipped-row entries in the CSVs are wrong\n",
             "`ex2_weak`'s shipped row in the two step-6 sweeps reads -100 % at two widths with a",
             "gate maximum of 0.00. Re-scored from the stored raws the shipped model is fine there",
             "(+6.0 / +15.1 / +28.5 / +47.2 / +75.7 %, a clean monotone ladder like the rest of the",
             "ex2 family) - the run had not finished when a parallel worker scored it, because the",
             "shipped runs are shared between the jobs of one device. The table above shows the",
             "re-scored values, marked †; the CSVs still hold the bad ones.",
             "",
             "Two of 301 sweeps are affected, both on the shipped reference row, none on a chain",
             "row, so no result depends on it. `endtoend.png` takes its shipped bars from the",
             "step-2f folder, which is clean.\n"]

    OUT.write_text(HEAD + "\n".join(body) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} buffers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
